im:
  tcpPort: 9001
  webSocketPort: 19001
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 # 心跳超时时间 单位毫秒
  logicUrl: http://127.0.0.1:8000/v1 # Feign RPC 调用业务层
  redis:
    mode: single # 单机模式:single 哨兵式:sentinel 集群模式:cluster
    database: 0
    password: sy991209!
    timeout: 3000  # 超时时间
    poolMinIdle: 4  #最小空闲数
    poolConnTimeout: 3000  # 连接超时时间(秒)
    poolSize: 10  # 连接池大小
    single:  #redis单机配置
      address: 124.222.135.79:6379
  rabbitmq:
    host: 124.222.135.79
    port: 5672
    virtualHost: /
    userName: guest
    password: guest
  zkConfig:
    zkAddr: 124.222.135.79:2181
    zkConnectTimeOut: 30000

#httpclient:
#  maxTotal: 100
#  defaultMaxPerRoute: 50
#  connectTimeout: 2000
#  connectionRequestTimeout: 2000
#  socketTimeout: 5000
#  staleConnectionCheckEnabled: true